### ISSUE TITLE
很棒！！！

### ISSUE THREAD

**Issue by Hopelsz** [beef-potato/MusicFreeThemes#2]
你好，我看啦你的主题，很棒哦~
偶然间发现一个小小的瑕疵，希望你别介意哈~这里字号有点看不清了
![image](https://github.com/beef-potato/MusicFreeThemes/assets/48856718/fb61da90-5cc4-4c54-8577-817742d53d89)

**Comment by beef-potato** [comment]
是我疏忽了，字体颜色改成白色应该考虑输入区的背景色，或者统一设置一个半透明的颜色
这么一看好多主题都没注意这块
